<?php

return [
    
        "Loft moderno con vista mozzafiato",
        "Appartamento elegante nel cuore della città",
        "Villetta con giardino spazioso",
        "Casa familiare con piscina privata",
        "Monolocale accogliente vicino al centro",
        "Chalet di montagna per gli amanti della natura",
        "Penthouse di lusso con vista panoramica",
        "Casa colonica ristrutturata con terreno",
        "Appartamento luminoso con balcone",
        "Cottage sul lago ideale per il relax",
        "Villa moderna in zona residenziale",
        "Loft spazioso con dettagli d'epoca",
        "Casa di campagna con vista sulle colline",
        "Appartamento con accesso alla spiaggia",
        "Chalet in stile alpino con camino",
        "Casa a schiera in quartiere tranquillo",
        "Appartamento con terrazza panoramica",
        "Villa di design con giardino lussureggiante",
        "Loft industriale con travi a vista",
        "Cottage rustico nel bosco",
        "Appartamento vicino a negozi e trasporti",
        "Chalet in montagna con sauna privata",
        "Casa con piscina e campo da tennis",
        "Appartamento con vista mare mozzafiato",
        "Villa con ampio spazio esterno",
        "Loft minimalista nel centro storico",
        "Casa familiare con spazi open-space",
        "Appartamento con cucina moderna",
        "Chalet con jacuzzi all'aperto",
        "Casa di lusso con parcheggio privato",
        "Appartamento con vista sulla città",
        "Villetta con ampio giardino e piscina",
        "Loft con atmosfera artistica",
        "Casa colonica con terreno agricolo",
        "Appartamento con caminetto",
        "Chalet in montagna con vista panoramica",
        "Casa a schiera in quartiere residenziale",
        "Appartamento con balcone panoramico",
        "Villa di lusso con servizi esclusivi",
        "Loft con arredi moderni",
        "Cottage sul lago con molo privato",
        "Appartamento in zona tranquilla",
        "Chalet in stile alpino con dettagli in legno",
        "Casa con giardino e spazio per animali",
        "Appartamento vicino a parchi e scuole",
        "Villa con piscina e area relax",
        "Loft con design contemporaneo",
        "Casa familiare con sala cinema",
        "Appartamento con terrazza panoramica",
        "Cottage in zona boschiva",
        "Chalet con camino e vasca idromassaggio",
        "Casa di campagna con vista collinare",
        "Appartamento con cucina open-space",
        "Villetta con giardino fiorito",
        "Loft industrial chic",
        "Appartamento con accesso alla spiaggia",
        "Chalet in montagna con sauna privata",
        "Casa a schiera in quartiere verde",
        "Villa con ampio spazio esterno",
        "Appartamento con vista mare spettacolare",
        "Cottage con camino e jacuzzi",
        "Chalet di lusso con servizi premium",
        "Casa moderna con spazi open-space",
        "Appartamento con balcone panoramico",
        "Loft con travi in legno a vista",
        "Casa colonica con terreno agricolo",
        "Appartamento con caminetto accogliente",
        "Chalet in montagna con vista mozzafiato",
        "Villa con piscina e campo da tennis privato",
        "Loft minimalista nel cuore della città",
        "Casa familiare con grande giardino",
        "Appartamento con cucina moderna e isola",
        "Cottage sul lago con accesso privato alla spiaggia",
        "Chalet in montagna con terrazza panoramica",
        "Casa a schiera in quartiere residenziale tranquillo",
        "Villetta con ampio giardino e piscina",
        "Appartamento luminoso e spazioso",
        "Casa moderna con dettagli d'epoca",
        "Loft con atmosfera artistica",
        "Appartamento con vista sulla città",
        "Cottage rustico nel bosco",
        "Chalet con jacuzzi e vista panoramica",
        "Casa di lusso con parcheggio privato",
        "Appartamento con design contemporaneo",
        "Villa con ampio spazio esterno e giardino lussureggiante",
        "Casa colonica ristrutturata con terreno agricolo",
        "Loft spazioso con caminetto e travi a vista",
        "Chalet di montagna con vista sulle vette",
        "Appartamento con cucina open-space e isola",
        "Casa familiare con sala cinema privata",
        "Villetta con piscina e area relax",
        "Appartamento luminoso con vista panoramica",
        "Casa di campagna con charme rustico",
        "Villetta in quartiere silenzioso",
        "Loft moderno nel cuore del centro storico",
        "Cottage accogliente con giardino privato",
        "Appartamento con doppio balcone",
        "Chalet di montagna con atmosfera romantica",
        "Villa elegante con piscina riscaldata",
        "Loft artistico in zona trendy",
        "Casa colonica con terreno e frutteto",
];