<?php

 return [
    "Ciao, sono interessato a soggiornare nella tua struttura per una settimana, vorrei informazioni su come spostarsi in zona.",
    "Buongiorno, sto cercando un alloggio nel tuo B&B per un fine settimana, potresti darmi informazioni sui prezzi e le disponibilità?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il mese prossimo. Mi puoi dire quali servizi inclusi sono disponibili?",
    "Ciao, sto pianificando un viaggio di lavoro nella tua zona. Puoi fornirmi dettagli sulla tua struttura e le tariffe?",
    "Buonasera, vorrei affittare una casa nel tuo B&B per un paio di settimane. Hai spazi disponibili?",
    "Salve, sto cercando un luogo accogliente per un soggiorno breve. Potresti fornirmi informazioni sulle attività nelle vicinanze?",
    "Ciao, sto pianificando una vacanza con la mia famiglia nella tua zona. Hai disponibilità per una casa?",
    "Buongiorno, sono interessato a prenotare una stanza nel tuo B&B. Mi puoi dire quali servizi extra offri?",
    "Salve, vorrei conoscere i dettagli sul check-in e sul check-out nella tua struttura per poter pianificare il mio viaggio.",
    "Ciao, sto cercando un alloggio economico nella tua zona. Potresti darmi informazioni sui costi del soggiorno nel tuo B&B?",
    "Salve, sto cercando un posto tranquillo per rilassarmi nel tuo B&B. Potresti darmi informazioni sulla tua struttura?",
    "Buongiorno, vorrei prenotare una casa nel tuo B&B per il prossimo weekend. Quali sono i dettagli sulla prenotazione?",
    "Ciao, sono interessato a soggiornare nella tua struttura per un mese. Mi puoi dire se hai offerte speciali per soggiorni prolungati?",
    "Salve, sto cercando un alloggio romantico per un anniversario. Puoi fornirmi dettagli sulla tua suite?",
    "Buongiorno, vorrei prenotare una stanza singola nel tuo B&B per una settimana. Quali sono i servizi inclusi?",
    "Ciao, sto pianificando una vacanza in famiglia. Hai spazi per ospitare una famiglia di quattro persone?",
    "Salve, sto cercando un B&B vicino a luoghi di interesse turistico. Quali attrazioni sono nelle vicinanze della tua struttura?",
    "Buongiorno, vorrei informazioni sulle tariffe per una casa nel tuo B&B. Mi puoi dare un preventivo?",
    "Ciao, sono interessato a prenotare una stanza nel tuo B&B per un fine settimana lungo. Quali sono i servizi extra disponibili?",
    "Salve, vorrei sapere se accetti animali domestici nel tuo B&B. Ho un cane di piccola taglia che mi piacerebbe portare con me.",
    "Buongiorno, sto cercando un alloggio con accessibilità per disabili. Hai stanze adatte a persone con mobilità ridotta?",
    "Ciao, sto pianificando un viaggio di lavoro nella tua zona. Hai tariffe speciali per viaggiatori d'affari nel tuo B&B?",
    "Salve, sono interessato a prenotare una stanza singola nel tuo B&B per una notte. Mi puoi dire se hai disponibilità?",
    "Buongiorno, sto cercando un luogo tranquillo per scrivere. La tua struttura offre un ambiente adatto agli scrittori?",
    "Ciao, sono interessato a soggiornare nel tuo B&B durante le festività. Hai programmi speciali o decorazioni natalizie?",
    "Salve, vorrei prenotare una casa per un gruppo di amici. Hai spazi per ospitare un gruppo di sei persone?",
    "Buongiorno, vorrei prenotare una stanza con vista panoramica. È possibile scegliere una stanza con una vista particolare?",
    "Ciao, sono interessato a prenotare una stanza doppia nel tuo B&B. Quali sono i servizi inclusi nella tariffa?",
    "Salve, sto cercando un B&B con una piscina. Hai una piscina accessibile agli ospiti?",
    "Buongiorno, vorrei informazioni sulla tua politica di cancellazione. Cosa succede se devo annullare la prenotazione?",
    "Ciao, sto pianificando una vacanza culinaria. Hai ristoranti o cucina locale nelle vicinanze?",
    "Salve, vorrei prenotare una stanza con balcone o terrazza. È possibile avere una stanza con spazio all'aperto?",
    "Buongiorno, vorrei prenotare una casa per un soggiorno di lunga durata. Quali sono le tariffe mensili?",
    "Ciao, sto cercando un B&B con un parcheggio sicuro. Hai un parcheggio custodito per gli ospiti?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il mio compleanno. Puoi aiutarmi a organizzare una sorpresa?",
    "Buongiorno, vorrei informazioni sulla tua politica sugli animali domestici. Quali sono le regole per portare animali con me?",
    "Ciao, sono interessato a prenotare una stanza con una vasca idromassaggio. Hai camere con questa caratteristica?",
    "Salve, sto cercando un luogo con un'atmosfera romantica per una proposta di matrimonio. Puoi aiutarmi a pianificarla?",
    "Buongiorno, vorrei prenotare una stanza nel tuo B&B per un soggiorno enogastronomico. Quali sono le opzioni nei dintorni?",
    "Ciao, sono interessato a soggiornare nel tuo B&B durante un festival locale. Hai sconti per eventi speciali?",
    "Salve, vorrei prenotare una camera familiare nel tuo B&B. Quali sono le tariffe per una famiglia di quattro persone?",
    "Buongiorno, sto cercando un luogo tranquillo per studiare. Hai spazi adatti per studenti?",
    "Ciao, sono interessato a prenotare una stanza doppia con letti separati. È possibile avere una stanza con questa configurazione?",
    "Salve, vorrei informazioni sulla tua politica di deposito. È richiesto un deposito al momento della prenotazione?",
    "Buongiorno, vorrei prenotare una casa per un soggiorno con amici. Hai aree comuni per trascorrere del tempo insieme?",
    "Ciao, sto pianificando un viaggio di nozze. Offri pacchetti speciali per coppie in luna di miele?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il prossimo festival musicale. Quali sono le opzioni nelle vicinanze?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B per un soggiorno artistico. Hai spazi per gli artisti?",
    "Ciao, sto cercando un alloggio con una vista panoramica. Posso vedere delle foto della vista dalla tua struttura?",
    "Salve, vorrei informazioni sulle attività all'aperto nella tua zona. Cosa posso fare durante il mio soggiorno?",
    "Buongiorno, vorrei prenotare una stanza singola nel tuo B&B per una notte. Quali servizi extra sono disponibili?",
    "Ciao, sono interessato a soggiornare nel tuo B&B durante un evento sportivo. Hai sconti per gli spettatori?",
    "Salve, vorrei prenotare una stanza doppia nel tuo B&B per un fine settimana romantico. Cosa offri di speciale per coppie?",
    "Buongiorno, vorrei informazioni sul servizio di pulizia delle stanze. Come funziona la pulizia durante il soggiorno?",
    "Ciao, sto cercando un B&B con una colazione inclusa. Offri la colazione per gli ospiti?",
    "Salve, vorrei prenotare una casa per un soggiorno di lunga durata. Quali sono le opzioni per la pulizia e il cambio biancheria?",
    "Buongiorno, sono interessato a prenotare una stanza per un viaggio di ricerca. Hai connessione internet ad alta velocità?",
    "Ciao, sto pianificando una visita invernale. La tua struttura offre riscaldamento adeguato?",
    "Salve, vorrei prenotare una camera familiare per il mio compleanno. Hai servizi speciali per ospiti festeggianti?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B durante un festival culinario. Hai sconti o eventi correlati?",
    "Ciao, sto cercando un B&B vicino a una stazione ferroviaria. Quanto dista la tua struttura dalla stazione più vicina?",
    "Salve, vorrei prenotare una stanza con un caminetto. È possibile avere una stanza con questa caratteristica?",
    "Buongiorno, vorrei informazioni sulle attività ricreative nelle vicinanze. Cosa c'è da fare durante il mio soggiorno?",
    "Ciao, sono interessato a prenotare una stanza singola nel tuo B&B per un viaggio di studio. Quali agevolazioni offri agli studenti?",
    "Salve, vorrei prenotare una stanza doppia con un balcone. Hai camere con questa caratteristica?",
    "Buongiorno, vorrei informazioni sulla politica di pagamento. Come posso effettuare il pagamento della prenotazione?",
    "Ciao, sto cercando un luogo tranquillo per scrivere. Offri spazi adatti agli scrittori?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per un soggiorno di relax. Quali servizi benessere offri?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B durante un evento artistico. Hai servizi o mostre d'arte correlate?",
    "Ciao, sto pianificando un viaggio di lavoro nella tua zona. Quali sono i servizi per i viaggiatori d'affari?",
    "Salve, vorrei prenotare una camera con una vista sul mare. Posso avere una stanza con questa vista?",
    "Buongiorno, vorrei informazioni sulle tariffe e le politiche di pagamento. Quali sono i dettagli sul prezzo del soggiorno?",
    "Ciao, sono interessato a prenotare una casa nel tuo B&B per una riunione di famiglia. Hai spazi per eventi o riunioni?",
    "Salve, vorrei prenotare una stanza singola nel tuo B&B per un fine settimana enogastronomico. Quali sono le opzioni nei dintorni?",
    "Buongiorno, sto cercando un B&B con accessibilità per disabili. Le tue stanze sono adatte a persone con mobilità ridotta?",
    "Ciao, sono interessato a prenotare una casa nel tuo B&B per un soggiorno enogastronomico. Quali ristoranti consigli nei dintorni?",
    "Salve, vorrei prenotare una stanza per un viaggio di nozze. Hai pacchetti speciali per coppie in luna di miele?",
    "Buongiorno, sto pianificando una vacanza invernale. Quali attività invernali sono disponibili nelle vicinanze della tua struttura?",
    "Ciao, sono interessato a soggiornare nel tuo B&B durante una festa locale. Hai programmi speciali o sconti per gli ospiti?",
    "Salve, vorrei prenotare una stanza doppia con vista sulle montagne. Posso avere una stanza con questa vista?",
    "Buongiorno, vorrei informazioni sulla politica di cancellazione. Quali sono le condizioni per l'annullamento delle prenotazioni?",
    "Ciao, sto cercando un B&B con servizi per famiglie. Hai servizi speciali per i bambini?",
    "Salve, vorrei prenotare una camera familiare nel tuo B&B per una festa di compleanno. Cosa offri per festeggiare?",
    "Buongiorno, sono interessato a prenotare una stanza con una vasca idromassaggio. Quali camere hanno questa caratteristica?",
    "Ciao, sto pianificando un viaggio di lavoro nella tua zona. Hai una connessione Wi-Fi affidabile?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il prossimo festival musicale. Quali band o artisti suoneranno in zona?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B durante un evento sportivo. Hai sconti o servizi speciali per gli spettatori?",
    "Ciao, sto cercando un luogo con una biblioteca. Hai una biblioteca o libreria nelle vicinanze della tua struttura?",
    "Salve, vorrei prenotare una stanza con una vista panoramica. Posso vedere delle foto della vista dalle camere?",
    "Buongiorno, vorrei informazioni sulle attività all'aperto. Quali sport o escursioni sono disponibili nei dintorni?",
    "Ciao, sono interessato a prenotare una stanza singola nel tuo B&B per un viaggio di studio. Quali agevolazioni offri agli studenti?",
    "Salve, vorrei prenotare una stanza doppia con un balcone o una terrazza. È possibile avere una stanza con questa caratteristica?",
    "Buongiorno, vorrei informazioni sulla politica di deposito. È richiesto un deposito al momento della prenotazione?",
    "Ciao, sto cercando un alloggio con un bar. Hai un bar o lounge nella tua struttura?",
    "Salve, vorrei prenotare una casa per un soggiorno con amici. Hai spazi comuni dove possiamo riunirci?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B durante un festival culinario. Offri corsi di cucina o eventi correlati?",
    "Ciao, sto pianificando una visita invernale. La tua struttura offre attività invernali come lo sci o le passeggiate sulla neve?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il mio compleanno. Puoi aiutarmi a organizzare una sorpresa?",
    "Buongiorno, sono interessato a prenotare una stanza con un caminetto. È possibile avere una stanza con questa caratteristica?",
    "Ciao, sto cercando un B&B vicino a un campo da golf. Quanto dista il campo da golf più vicino dalla tua struttura?",
    "Salve, vorrei prenotare una camera familiare nel tuo B&B per una vacanza con la mia famiglia. Quali sono i dettagli sulla tariffa?",
    "Buongiorno, vorrei informazioni sulla tua politica sugli animali domestici. Posso portare il mio gatto con me durante il soggiorno?",
    "Ciao, sono interessato a prenotare una casa nel tuo B&B per una riunione di lavoro. Hai spazi per riunioni o conferenze?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per un soggiorno romantico. Cosa offri di speciale per coppie?",
    "Buongiorno, vorrei prenotare una stanza con vista sul fiume. Posso avere una stanza con questa vista?",
    "Ciao, sto pianificando una vacanza estiva. Quali attività estive sono disponibili nelle vicinanze della tua struttura?",
    "Salve, vorrei informazioni sulla politica di pagamento. Posso pagare con carta di credito o altri metodi di pagamento?",
    "Buongiorno, sono interessato a prenotare una stanza nel tuo B&B per un soggiorno culinario. Quali ristoranti consigli nella zona?",
    "Ciao, sto cercando un B&B con una piscina. Hai una piscina accessibile agli ospiti?",
    "Salve, vorrei prenotare una stanza per un viaggio di nozze. Hai pacchetti speciali per coppie in luna di miele?",
    "Buongiorno, sto pianificando una vacanza invernale. La tua struttura offre attività invernali come lo sci o le passeggiate sulla neve?",
    "Ciao, sono interessato a soggiornare nel tuo B&B durante una festa locale. Hai programmi speciali o sconti per gli ospiti?",
    "Salve, vorrei prenotare una stanza con vista panoramica. Posso vedere delle foto della vista dalle camere?",
    "Buongiorno, vorrei informazioni sulle attività all'aperto. Quali sport o escursioni sono disponibili nelle vicinanze?",
    "Ciao, sono interessato a prenotare una stanza singola nel tuo B&B per un viaggio di studio. Quali agevolazioni offri agli studenti?",
    "Salve, vorrei prenotare una stanza doppia con un balcone o una terrazza. È possibile avere una stanza con questa caratteristica?",
    "Buongiorno, vorrei informazioni sulla politica di deposito. È richiesto un deposito al momento della prenotazione?",
    "Ciao, sto cercando un alloggio con un bar. Hai un bar o lounge nella tua struttura?",
    "Salve, vorrei prenotare una casa per un soggiorno con amici. Hai spazi comuni dove possiamo riunirci?",
    "Buongiorno, sono interessato a soggiornare nel tuo B&B durante un festival culinario. Offri corsi di cucina o eventi correlati?",
    "Ciao, sto pianificando una visita invernale. La tua struttura offre attività invernali come lo sci o le passeggiate sulla neve?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per il mio compleanno. Puoi aiutarmi a organizzare una sorpresa?",
    "Buongiorno, sono interessato a prenotare una stanza con un caminetto. È possibile avere una stanza con questa caratteristica?",
    "Ciao, sto cercando un B&B vicino a un campo da golf. Quanto dista il campo da golf più vicino dalla tua struttura?",
    "Salve, vorrei prenotare una camera familiare nel tuo B&B per una vacanza con la mia famiglia. Quali sono i dettagli sulla tariffa?",
    "Buongiorno, vorrei informazioni sulla tua politica sugli animali domestici. Posso portare il mio gatto con me durante il soggiorno?",
    "Ciao, sono interessato a prenotare una casa nel tuo B&B per una riunione di lavoro. Hai spazi per riunioni o conferenze?",
    "Salve, vorrei prenotare una stanza nel tuo B&B per un soggiorno romantico. Cosa offri di speciale per coppie?",
    "Buongiorno, vorrei prenotare una stanza con vista sul fiume. Posso avere una stanza con questa vista?",
    "Ciao, sto pianificando una vacanza estiva. Quali attività estive sono disponibili nelle vicinanze della tua struttura?",
    "Salve, vorrei informazioni sulla politica di pagamento. Posso pagare con carta di credito o altri metodi di pagamento?"
];

// Ora puoi utilizzare l'array $messaggi per gestire le richieste dei potenziali acquirenti.
