<?php
return [
    "Colazione inclusa",
    "Wi-Fi gratuito",
    "Parcheggio gratuito",
    "Reception 24 ore su 24",
    "Camere con bagno privato",
    "Aria condizionata",
    "Riscaldamento centralizzato",
    "TV a schermo piatto",
    "Servizio di pulizia giornaliero",
    "Cambio biancheria",
    "Asciugacapelli in camera",
    "Prodotti da bagno gratuiti",
    "Servizio in camera",
    "Cassaforte in camera",
    "Accesso per disabili",
    "Terrazza o balcone privato",
    "Servizio di lavanderia",
    "Servizio di navetta per l'aeroporto",
    "Assistenza turistica",
    "Biciclette a noleggio",
    "Ristorante in loco",
    "Bar o lounge",
    "Piscina all'aperto",
    "Spa e centro benessere",
    "Palestra o centro fitness",
    "Sala conferenze",
    "Servizio di babysitter",
    "Animali domestici ammessi",
    "Servizio di noleggio auto",
    "Servizio navetta per le attrazioni locali",
    "Camere per non fumatori",
    "Deposito bagagli",
    "Servizio di concierge",
    "Check-in/check-out veloce",
    "Sala giochi",
    "Piscina coperta",
    "Jacuzzi o vasca idromassaggio",
    "Giardino o spazio all'aperto",
    "Servizio di catering per eventi",
    "Camino o caminetto",
    "Biblioteca",
    "Servizio in camera 24 ore su 24",
];